#!/usr/bin/env bash
# Remove project-local files generated by dependency and skill installation.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

node <<'NODE'
const fs = require("node:fs");
const path = require("node:path");

const repoRoot = process.cwd();
const inRepoSkillRoots = new Set();

function removePath(target) {
  fs.rmSync(target, { recursive: true, force: true });
}

function collectInRepoSkills() {
  const skillsRoot = path.join(repoRoot, "skills");
  if (!fs.existsSync(skillsRoot)) {
    return;
  }

  for (const entry of fs.readdirSync(skillsRoot, { withFileTypes: true })) {
    if (entry.isDirectory() && fs.existsSync(path.join(skillsRoot, entry.name, "SKILL.md"))) {
      inRepoSkillRoots.add(entry.name);
    }
  }
}

function cleanSkillOverlay(root) {
  if (!fs.existsSync(root)) {
    return;
  }

  for (const entry of fs.readdirSync(root, { withFileTypes: true })) {
    if (!inRepoSkillRoots.has(entry.name)) {
      removePath(path.join(root, entry.name));
    }
  }
}

collectInRepoSkills();
removePath(path.join(repoRoot, "node_modules"));

for (const entry of fs.readdirSync(repoRoot, { withFileTypes: true })) {
  if (entry.name === ".skills-install.lock" || /^\.skills-install\.lock\..*\.tmp$/.test(entry.name)) {
    removePath(path.join(repoRoot, entry.name));
  }
}

cleanSkillOverlay(path.join(repoRoot, ".agents", "skills"));
cleanSkillOverlay(path.join(repoRoot, ".claude", "skills"));
NODE

echo "clean: removed generated dependency and skill install files"
